### ISSUE TITLE
source rvm before running bundler

### ISSUE THREAD

**Issue by spuder** [benbria/dashing-chef#3]
I've been trying for a few days to get this cookbook working. Don't have it yet. 

The biggest problem is that the bash script which calls 'bundler' runs a root, and doesn't source the rvm file (if present). It results in errors like this. 

```bash

             ================================================================================
             Error executing action `run` on resource 'script[devops-dashboard - bundle]'
             ================================================================================

             Mixlib::ShellOut::ShellCommandFailed
             ------------------------------------
             Expected process to exit with [0], but received '1'
             ---- Begin output of "bash"  "/tmp/chef-script20150716-7661-1lgplas" ----
             STDOUT: Using /usr/local/rvm/gems/ruby-1.9.3-p385
             STDERR: /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/dependency.rb:315:in `to_specs': Could not find 'bundler' (>= 0) among 41 total gem(s) (Gem::LoadError)

             	from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/dependency.rb:324:in `to_spec'
             	from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_gem.rb:58:in `gem'
             	from /opt/chef/embedded/bin/bundle:22:in `<main>'
             ---- End output of "bash"  "/tmp/chef-script20150716-7661-1lgplas" ----
             Ran "bash"  "/tmp/chef-script20150716-7661-1lgplas" returned 1

             Cookbook Trace:
             ---------------
             /tmp/kitchen/cookbooks/dashing/providers/dashboard.rb:162:in `setup_dashboard'
             /tmp/kitchen/cookbooks/dashing/providers/dashboard.rb:38:in `block in class_from_file'

             Resource Declaration:
             ---------------------
             # In /tmp/kitchen/cookbooks/dashing/providers/dashboard.rb

             135:         script "#{get_dashboard_name()} - bundle" do
             136:             interpreter "bash"
             137:             user "root"
             138:             cwd cached_new_resource.path
             139:             code <<-EOH
             140:
       141:             # Quit on error
             142:             set -e
             143:
             144:             #{node["dashing"]["ruby_env"]}
             145:             bundle
             146:
             147:             EOH
             148:
             149:         end
             150:         # Create startup scripts, and delete old scripts if the service type has changed.


             ------------------
             # Declared in /tmp/kitchen/cookbooks/dashing/providers/dashboard.rb:135:in `setup_dashboard'

             script("devops-dashboard - bundle") do
        action [:run]
        retries 0
        retry_delay 2
        default_guard_interpreter :default
        command "devops-dashboard - bundle"
        backup 5
        cwd "/opt/dashing/devops-dashboard"
        returns 0
        user "root"
        code "\n            # Quit on error\n            set -e\n\n            source /etc/profile.d/rvm.sh && rvm use ruby-1.9.3-p385\n            bundle\n\n"
        interpreter "bash"
        declared_type :script
        cookbook_name :"nd-dashing"
             end



           ================================================================================
           Error executing action `create` on resource 'dashing_dashboard[/opt/dashing/devops-dashboard]'
           ================================================================================

           Mixlib::ShellOut::ShellCommandFailed
           ------------------------------------
           script[devops-dashboard - bundle] (/tmp/kitchen/cookbooks/dashing/providers/dashboard.rb line 135) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
           ---- Begin output of "bash"  "/tmp/chef-script20150716-7661-1lgplas" ----
           STDOUT: Using /usr/local/rvm/gems/ruby-1.9.3-p385
           STDERR: /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/dependency.rb:315:in `to_specs': Could not find 'bundler' (>= 0) among 41 total gem(s) (Gem::LoadError)
           Checked in 'GEM_PATH=/usr/local/rvm/gems/ruby-1.9.3-p385:/usr/local/rvm/gems/ruby-1.9.3-p385@global', execute `gem env` for more information
       from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/dependency.rb:324:in `to_spec'
           	from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_gem.rb:58:in `gem'
           	from /opt/chef/embedded/bin/bundle:22:in `<main>'
           ---- End output of "bash"  "/tmp/chef-script20150716-7661-1lgplas" ----
           Ran "bash"  "/tmp/chef-script20150716-7661-1lgplas" returned 1

           Cookbook Trace:
           ---------------
           /tmp/kitchen/cookbooks/dashing/providers/dashboard.rb:162:in `setup_dashboard'
           /tmp/kitchen/cookbooks/dashing/providers/dashboard.rb:38:in `block in class_from_file'

           Resource Declaration:

           # In /tmp/kitchen/cookbooks/nd-dashing/recipes/default.rb

            39: dashing_dashboard "/opt/dashing/devops-dashboard" do
            40:   action :create
            41:   port 9090
            42: end


           ------------------
           # Declared in /tmp/kitchen/cookbooks/nd-dashing/recipes/default.rb:39:in `from_file'

           dashing_dashboard("/opt/dashing/devops-dashboard") do
             action [:create]
             updated true
             updated_by_last_action true
             retries 0
             retry_delay 2
             default_guard_interpreter :default
         declared_type :dashing_dashboard
             cookbook_name :"nd-dashing"
             recipe_name "default"
             port 9090
             service_type "upstart"
             path "/opt/dashing/devops-dashboard"
           end



       ---- Begin output of "bash"  "/tmp/chef-script20150716-7661-1lgplas" ----
       STDOUT: Using /usr/local/rvm/gems/ruby-1.9.3-p385
       STDERR: /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/dependency.rb:315:in `to_specs': Could not find 'bundler' (>= 0) among 41 total gem(s) (Gem::LoadError)
       Checked in 'GEM_PATH=/usr/local/rvm/gems/ruby-1.9.3-p385:/usr/local/rvm/gems/ruby-1.9.3-p385@global', execute `gem env` for more information
       	from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/dependency.rb:324:in `to_spec'
       	from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_gem.rb:58:in `gem'
       	from /opt/chef/embedded/bin/bundle:22:in `<main>'
       ---- End output of "bash"  "/tmp/chef-script20150716-7661-1lgplas" ----
```

This proabably could be worked around by sourcing the rvm config files first, but I'm not sure that is a good idea since people could have ruby installed in different ways (rvm-user install, rvm-machine wide install) ect.. 

Before I take the time to develop a pull request that might break the philosophy of being 'ruby environment agnostic',  I'm curious what the recommended ruby setup would be that might prevent this problem. (In other words, how did you get it to work?).

**Comment by jwalton** [comment]
I wrote this a long time ago and haven't looked at it in a while.  I also now deploy my dashing dashboard via ansible.  But, at one point in time I had this working on a vanilla Vagrant Ubuntu box.

Digging through my project history...

In attributes/default.rb (I suspect `override["dashing"]["ruby_env"]` is what you're looking for):

```
default["dashboard"]["ruby_version"] = "ruby-1.9.3-p385"

# Because we're using RVM
override["dashing"]["ruby_env"]      = "source /etc/profile.d/rvm.sh && rvm use #{node["dashboard"]["ruby_version"]}"

# Because we're using NVM
override["dashing"]["js_env"]        = "source /usr/local/src/nvm/nvm.sh && nvm use #{node["nodejs"]["version"]}"
```

And then I'd use the rvm@0.9.1 cookbook to run:

```
# Update packages
include_recipe 'apt'

...

# Install NVM
include_recipe 'nvm'
nvm_install node["nodejs"]["version"] do
    from_source false
    alias_as_default true
    action :create
end

# Install Ruby + RVM
include_recipe 'rvm::system_install'
rvm_ruby node["dashboard"]["ruby_version"]

# Install Dashing
include_recipe 'dashing::default'

# Deploy our dashboard
include_recipe 'dashboard::deploy_dashboard'
```

Finally, over in delpoy_dashboard.rb, I had some hacky special case code for deploying to vagrant vs. a real server.

```
is_vagrant = node['instance_role'] == 'vagrant'

if is_vagrant
    script "install_dashboard" do
        interpreter "bash"
        user "root"
        code <<-EOH
            mkdir -p #{node["dashboard"]["install_dir"]}/current
            rsync -a --delete /vagrant/ #{node["dashboard"]["install_dir"]}/current/
        EOH
    end

else
    script "install_dashboard" do
        interpreter "bash"
        user "root"
        code <<-EOH
            mkdir -p #{node["dashboard"]["install_dir"]}/current
            cp #{node["dashboard"]["install_dir"]}/current/dashing-dashboard/history.yml /tmp
            rsync -a --delete ~ubuntu/chef-install/ #{node["dashboard"]["install_dir"]}/current/
            cp /tmp/history.yml #{node["dashboard"]["install_dir"]}/current/dashing-dashboard
        EOH
    end

end

dashing_dashboard "#{node["dashboard"]["install_dir"]}/current/dashing-dashboard" do
    action :restart
    port node["dashboard"]["listen_port"]
end
```

Hope that helps.

**Comment by spuder** [comment]
Thanks for the quick response and the great info. Ansbile looks really great. I'll have to try it someday. 

I tried this, and it appears to have worked around the problem where bundler isn't installed.  

```yaml
    attributes:
      dashing:
        service_type: 'upstart'
        ruby_env: 'source /etc/profile.d/rvm.sh && rvm use ruby-1.9.3-p385 && gem install bundler && gem install dashing'
        js_env: 'source /usr/local/src/nvm/nvm.sh && nvm use v0.8.16'
 'source /etc/profile.d/rvm.sh && rvm use ruby-1.9.3-p385 && gem install bundler && gem install dashing'

```

I"m still encountering some other problems like the upstart script not being executed. I'll compare what you posted to what I have. Thanks.

**Comment by spuder** [comment]
Finally got it working. 

For posterity, here is a working config. 

https://gist.github.com/spuder/519e605a03eab9c2a136

Still needs a nginx proxy, but works well enough.

**Comment by jwalton** [comment]
Thanks!

**Comment by jwalton** [comment]
Added this to the READM.md.  Thanks again!
